#h2 console 활성화 및 경로 설정
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
#h2 db 설정
  datasource:
    url: jdbc:h2:~/test;
    driverClassName: org.h2.Driver
    username: sa
    password:
#hibernate 설정
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        ddl-auto: create
        dialect: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.H2Dialect
